### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by ABKQPO** [Agnes4m/nonebot_plugin_AL#1]
06-04 07:00:26 [ERROR] nonebot | Failed to import "nonebot_plugin_al"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_al\__init__.py", line 14, in <module>
    __plugin_meta__ = PluginMetadata(
TypeError: PluginMetadata.__init__() got an unexpected keyword argument 'type'

**Comment by Agnes4m** [comment]
确保nb版本是2.0.0而不是2.0.0rc4或者更早，如果发现更新不了，请别使用清华源，个人推荐腾讯源或者阿里源
